### ISSUE TITLE
Unable to use getFixtures2 to get a list of my fixtures

### ISSUE THREAD

**Issue by vitalybe** [react-cosmos/react-cosmos#1238] opened 2020-07-26 22:23 UTC
Hi,

I'm trying to get visual testing working with cosmos (Percy). To do that I've been trying the last couple of hours to make `getFixtures2` run with `node`:

```
import { detectCosmosConfig, getFixtures2 } from "react-cosmos";
const config = detectCosmosConfig();
const fixtures = getFixtures2(config);
console.log(fixtures);
```

My initial problems were trying to combine CommonJS and ES6 imports. However, I soon realized that this code is basically trying to dynamically load **all** my frontend code, that's written in TypeScript. So I've tried using both **ts-node** and **esm**. However, I failed at both with rather cryptic errors.

Eventually, I've tried to use **jest**, as it is what cosmos example uses. I figured it is the safest way, since I am using jest to test my code too. That one ran for 25 seconds that failed too with `require.context is not a function`.

Is there an easier way to get it working? I was thinking that since cosmos is already running anyway and since it already knows all its fixtures, it would be much easier if it exposed some kind of JSON endpoint that lists all the fixtures, i.e., something like: `http://dev-localhost.cqloud.com:5000/fixtures.json`. Is there something like that?

Or am I missing something much more basic and there is an easier way to run `getFixtures2`?

**Comment by skidding** [comment] 2020-07-31 20:40
Hi @vitalybe! Sorry for the late reply.

> However, I soon realized that this code is basically trying to dynamically load all my frontend code

This is correct. Not necessarily _all_ your frontend code, however, just the one your fixtures depend on.

> Is there an easier way to get it working? I was thinking that since cosmos is already running anyway and since it already knows all its fixtures, it would be much easier if it exposed some kind of JSON endpoint that lists all the fixtures, i.e., something like: http://dev-localhost.cqloud.com:5000/fixtures.json. Is there something like that?

Unfortunately there isn't. `getFixtures2` needs to "open" fixtures to read the fixture names, and you can only do that by importing the fixture modules.

But this is a good idea. You're right, since the dev server / playground is already running when doing visual regression testing, you can ask it to give you the fixtures without reading them on the server. Note that this doesn't apply to JSON snapshot testing, which doesn't use a live dev server to generate the snapshots.

I'm a bit caught up with making progress on the plugin system lately (which is long overdue), but it would be very helpful if you moved the discussion to an RFC proposal so we can iron out the details: https://github.com/react-cosmos/rfcs. We could add another method called `getLiveFixtures` or something, which gets them via the live dev server.

> That one ran for 25 seconds that failed too with require.context is not a function.

I haven't encountered this, but maybe your frontend code uses the wildcard import `xxx/*` feature supported by webpack?

**Comment by skidding** [comment] 2020-08-18 22:12
> We could add another method called getLiveFixtures or something, which gets them via the live dev server.

I've given this some thought and it's more complicated than anticipated. I don't want to get to deep into it, but we can't make a Cosmos server endpoint that will return all fixture data (including module exports), because that would require the Cosmos server to _open_ the fixture modules, something that can only be safely done in the user build, which only generates a bundle and I don't really know how to make it export the json we're looking for.

That said, I think there is a way for you to **make require.context work in Jest**. Check out [this StackOverflow response](https://stackoverflow.com/a/54151648/128816) about [this Babel plugin](https://www.npmjs.com/package/babel-plugin-require-context-hook). You can also follow the steps in "Option 1: Plugin" from [this section](https://github.com/storybookjs/storybook/tree/091c706838f8a73f63b1e4c0a4e17f7b47637471/addons/storyshots/storyshots-core#option-1-plugin) of the Storybook docs.

@vitalybe Please let me know if you try this, because if it works I'd like to add a FAQ entry for this situation. Thanks.

**Comment by skidding** [comment] 2023-03-03 16:24
Not relevant anymore so closing this. `getFixtures` not longer uses `require.context`.

**Closed by skidding** 2023-03-03 16:24 UTC
