### ISSUE TITLE
Collapsible and smarter component list

### ISSUE THREAD

**Issue by ovidiubute** [react-cosmos/react-cosmos#251] opened 2017-01-02 09:13 UTC
### Problem
If you have more than 10 components in your app, with at least 2 or 3 fixtures each, the component list is pretty daunting to look at. To be able to find something you need to use the search feature, but this should not be the only way to find something.

### Proposed solution
- Make the component list expandable, i.e. each item in the list that is a component name should have an icon next to it (or maybe the item itself should be clickable) that triggers the collapse/expand of its fixture list. The fixture list should animate when opening/closing.
- When you start the Playground for the first time, all components should be collapsed by default except the first one with at least 1 user-defined fixture (first component that has more fixtures than just (no-props auto))
- As you use Playground, the fixtures most often used could be tracked via local storage. Thus, when reloading the Playground, instead of having all of the fixtures collapsed, the most recently or most commonly used components (to be discussed) could have their fixture list expanded.

**Comment by ovidiubute** [comment] 2017-01-02 09:15
@skidding please review

**Comment by skidding** [comment] 2017-01-02 16:04
Yes!

> When you start the Playground for the first time, all components should be collapsed by default except the first one with at least 1 user-defined fixture

Not sure about this. Maybe if we do a good job with oboarding #252 this isn't needed.

> As you use Playground, the fixtures most often used could be tracked via local storage. Thus, when reloading the Playground, instead of having all of the fixtures collapsed, the most recently or most commonly used components (to be discussed) could have their fixture list expanded.

❤️ it. I think the easiest implementation is to simply remember the last expanded components (list of name strings) between visits.

Extra thoughts:
- The CP is known to be a monster component. Now is a good time to extract a Nav component out of it. Besides the isolation of concerns, writing tests in the old suite is painful (it was designed poorly) and this is an opportunity to rewrite the nav UI part and make it an ES6 class tested with Jest.
- One think I find misleading about the current search mechanism is how the selected component remains visible regardless of the search input. I think it should only show the matched fixtures and "no results" when there aren't any. Completely optional, but maybe we could bundle this improvement as well (unless you feel otherwise).

**Comment by skidding** [comment] 2017-01-02 18:17
One more thing: It would be cool if we would separate components with fixtures from components without fixtures, in this order. The benefits are twofold:
- You see the components you have created fixtures for first
- The list buttons can diff between sections. E.g. components without fixtures shouldn't be collapsable and instead of having a "no props (auto)" fixture the component name itself could be the button.

**Comment by jlc467** [comment] 2017-03-11 17:20
With this idea, does the component's location become a tooltip? Right now, the component's location is part of the item text, which doesn't take much to cut off (see below).
![screen shot 2017-03-11 at 12 00 29 pm](https://cloud.githubusercontent.com/assets/6405557/23825173/b489ee46-0652-11e7-925b-9e086a2cf861.png)

I imagine the component location was included to avoid confusion when a component shares the name with another component in another folder. If I had to choose though, I'd rather see just the component name (with location as a tooltip), and use the search bar to narrow in a specific folder as pictured above. Just 2cents from someone that has a project with 3 level deep folder nesting.

As far as splitting between with/without fixtures... In my case, I had so many components that didn't make sense to show in cosmos at all without me adding fixtures and making them more "independent." So what I ended up doing is using an exclude filter in the cosmos config to only include components with "IC" in the file name. Depending on implementation, splitting with/without would accomplish the same thing in a cleaner way.

**Comment by skidding** [comment] 2017-03-11 18:26
> With this idea, does the component's location become a tooltip? 

More than that. We'll show just the component name (without namespace), but components will be grouped per nested sections. Something like a tree view, since as you said you we can have 3 levels or more of nesting. How the tree view will look is up for debate. A classic tree view is straightforward, but you lose a lot of space with the padding from each indentation level. Another option would be to only show one nesting level at a time (except when searching), and have a sort of sliding navigation left to right as you open folders or go back.

Glad you agree on the with/without split. We'll invest some time in making the left nav great after the 2.0 release.

**Comment by jlc467** [comment] 2017-03-11 22:16
Just gonna leave these tree view components here for reference later:
http://alexcurtis.github.io/react-treebeard/
https://ant.design/components/tree/#components-tree-demo-search
https://cdn.rawgit.com/chenglou/react-treeview/aa72ed8b9e0b31fabc09e2f8bd4084947d48bb09/demos/index.html

**Comment by amrdraz** [comment] 2017-07-24 14:47
This is relevant to me, can I work on this over the weekend?
I'm thinking of http://alexcurtis.github.io/react-treebeard/

**Comment by skidding** [comment] 2017-07-24 16:05
Yes! I'll assign you to make sure nobody overlaps. 

react-treebeard demo looks nice, we just need to make sure whatever lib we use is not bloated or buggy.

**Comment by amrdraz** [comment] 2017-07-31 05:44
Checkin update this weekend was spent on an urgent work related project ( my project is close to getting bloated enough in components to really need this though 😅  )

**Comment by amrdraz** [comment] 2017-09-07 03:52
started a pull request with a prototype please review ui ux

![screen shot 2017-09-07 at 05 36 52 copy](https://user-images.githubusercontent.com/1708559/30145117-7bcf13a4-938f-11e7-9077-2022435aa863.jpg)

tree-bed was super bloated so I built the tree view myself and added it as a subcomponent
I did not change the current search system nor the save state of tree

changing the search is a matter of changing how fixtures are filtered (I can make it more like the treebed demo showing only the relevant fixtures)

I support merging trees so it's possible to save the state of the tree
however I don't find it that useful yet

any node in the tree when clicked will call the onNodeClick or onLeafClick hook passing the node
a node contains its name, path (up to this point), value (in case of leaf) and children etc

right now I set as value for each leaf the fixtures and component which is then used to update the url onClick

what else needs to happen?

**Comment by amrdraz** [comment] 2017-09-07 10:14
just came across this
https://github.com/farzher/fuzzysort

**Comment by skidding** [comment] 2017-09-08 19:39
Wow, this looks exciting. Will review soon!

**Comment by skidding** [comment] 2017-10-17 08:56
Happy to say this feature (the oldest issue) has been added in #448

@maxsalven will likely add tree view persistence in a subsequent PR, and together with #469 will be part of a new major release. 🚂

**Closed by skidding** 2017-10-17 08:56 UTC
Labels: i have a dream, needs love

**Comment by dmr** [comment] 2017-11-08 07:24
Thank you very much. I really enjoy the new tree, great work!
