### ISSUE TITLE
Error: ENAMETOOLONG with cosmos-export

### ISSUE THREAD

**Issue by NiGhTTraX** [react-cosmos/react-cosmos#415] opened 2017-08-25 06:11 UTC
### What's up?

```
node_modules/.bin/cosmos-export --config playground/cosmos.config.js
[Cosmos] Using webpack config found at src/webpack.config.dev.js
node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:49
          throw err0
          ^

Error: ENAMETOOLONG: name too long, mkdir 'playground/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export/loader/cosmos-export'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Object.mkdirsSync (node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at copySync (node_modules/fs-extra/lib/copy-sync/copy-sync.js:49:37)
    at contents.forEach.content (node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:7)
    at Array.forEach (native)
    at copySync (node_modules/fs-extra/lib/copy-sync/copy-sync.js:51:14)
    at contents.forEach.content (node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:7)
    at Array.forEach (native)
    at copySync (node_modules/fs-extra/lib/copy-sync/copy-sync.js:51:14)
    at contents.forEach.content (node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:7)
    at Array.forEach (native)
    at copySync (node_modules/fs-extra/lib/copy-sync/copy-sync.js:51:14)
    at contents.forEach.content (node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:7)
    at Array.forEach (native)
    at copySync (node_modules/fs-extra/lib/copy-sync/copy-sync.js:51:14)
```

### Mkay, tell me more...

If I remove `publicPath` from my [cosmos config](https://github.com/NiGhTTraX/react-test-buffet/blob/70b2a0eeebe1403abaaa8b1c7cfec2899aa98308/playground/cosmos.config.js) then it works. It also works if I comment out [these lines](https://github.com/react-cosmos/react-cosmos/blob/299fc740426ac08b8dcdb31017fb84a1b0e3ec40/packages/react-cosmos-webpack/src/export.js#L79-L82) in the export script.

**Comment by skidding** [comment] 2017-08-25 09:45
The problem is your publicPath is set to `./playground` and the export path (outputPath) is set to `./plaground/cosmos-export`. So trying to copy `./playground` in `./plaground/cosmos-export` creates an infinite loop. Two things:

- I created [this PR](https://github.com/react-cosmos/react-cosmos/pull/416) to prevent this in the future. Please take a look.
- Why are you setting the publicPath to `./playground`? The public path is meant for static files, of which you seem to have none. So you might as well remove the option altogether. Fun fact, did you know that you're statically serving the `./playground` dir, along with the cosmos config? 😄 

![image](https://user-images.githubusercontent.com/250750/29708765-331fcb08-898a-11e7-958c-905ad4556c6c.png)

**Comment by NiGhTTraX** [comment] 2017-08-26 11:46
Huh, interesting. I thought `publicPath` acted like [webpack's option](https://webpack.js.org/configuration/output/#output-publicpath) which is used to set the CDN. For webpack it's relative to the page serving the files so that's why I set it to `./`.

Why do you need to copy the `publicPath` folder when exporting? Can you give me an example of how you would use the option in the playground?

**Comment by skidding** [comment] 2017-08-26 11:59
> Huh, interesting. I thought publicPath acted like webpack's option which is used to set the CDN. For webpack it's relative to the page serving the files so that's why I set it to ./.

It's more like [webpackDevServer's contentBase option](https://webpack.js.org/configuration/dev-server/#devserver-contentbase).

> Why do you need to copy the publicPath folder when exporting? Can you give me an example of how you would use the option in the playground?

Static assets that aren't loaded via webpack. Like a webfont that you put in `public/MyWebfont.woff` and then reference it in your index.html directly. It depends on each person's config and Create React App discourages it. But in Next.js for example you have `/static/` serving the `static` directory. So you'd make that work with Cosmos like this:

```js
// cosmos.config.js
publicPath: 'static',
publicUrl: '/static/',
```

**Comment by NiGhTTraX** [comment] 2017-08-26 12:04
Ah ok, so it's just for stuff referenced outside of files parsed by webpack. Kinda like `globalImports`, right? Speaking of which, how do you handle `globalImports` when exporting?

I think a different name would've avoided the confusion for me. `staticPath`, perhaps?

**Comment by skidding** [comment] 2017-08-26 12:09
> Ah ok, so it's just for stuff referenced outside of files parsed by webpack. Kinda like globalImports, right?

In concept, yeah, but stuff from the publicPath are static, unprocessed assets.

> Speaking of which, how do you handle globalImports when exporting?

They will be part of the resulting bundle. The webpack bundle will have multiple entry points, same as it works in development.

> I think a different name would've avoided the confusion for me. staticPath, perhaps?

Good idea. publicUrl should also become staticUrl, in this case. I'm open to this change but it needs a deprecation strategy.

**Closed** 2017-08-26 12:28 UTC
Labels: oops
