### ISSUE TITLE
Compose update-props-proxy to test stateless components in a handy way

### ISSUE THREAD

**Issue by dfedynich** [react-cosmos/react-cosmos#431] opened 2017-09-07 13:31 UTC
### What's up?

It will be great to inject some new life in react stateless components during the testing in cosmos environment. The usual way to invert data flow in a react app is to set the state somewhere in the top of components' hierarchy and pass handlers to get new values from stateless components. Then save new values in the state and pass them back via new props. Here is the well-known [Thinking in React](https://facebook.github.io/react/docs/thinking-in-react.html) article to describe the idea in details.

So, if we create a fixture for the stateless component, we will get no chances to make any UI changes in the current implementation. To make them alive we need to mock component handlers to get the new values and pass them back via props. Update-props-proxy is the suggested solution. What to do you think about the idea?

### Mkay, tell me more...

Generally, the proxy will get the updated values from the specified handlers in the fixture prop and store them in the state. Then it will pass the values from the state to the appropriate component's props. 
If you like the idea, just let me know, and I can create a pull request in the nearest time.

**Comment by skidding** [comment] 2017-09-07 14:26
I think I know what you mean, and I'm a fan!

I've thought about this a couple of times and I've also touched on this subject a few months ago with @markdalgleish. If I'm not mistaken he already created something similar in their custom component explorer at SEEK.

So if I understand correctly, you're talking about a way to enable fixture handlers (callbacks) to mutate the fixture and essentially change the props as you interact with a stateless component. This is how I envision it:

```js
// ...inside a fixture file
import { fixtureUpdater } from 'react-cosmos-foo-bar';

export default {
  props: {
    name: 'Denis Fedynich',
    onChange: fixtureUpdater((fixture, value) => ({
      ...fixture,
      props: {
        ...fixture.props,
        name: value
      }
    }))
  }
};
```

Is this how you see it, or differently?

PS. This allows mutating the entire fixture, not just the props.

**Comment by dfedynich** [comment] 2017-09-08 14:38
Yes, you got the idea. We are on the same page, I think.
I implemented the proxy in a quick way, so it gets the updated values from the specified handlers in the fixture prop and stores them in the state. Then it passes the values from the state to the appropriate component's props.

```
import React from 'react';
import invariant from 'invariant'
import _isNil from 'lodash/isNil';

const defaults = {
    fixtureKey: 'handlers'
};

export default function updatePropsProxy(options) {
    const { fixtureKey } = { ...defaults, ...options };

    class UpdatePropsProxy extends React.PureComponent {
        constructor(props) {
            super(props);
            this.state = {};

            const handlers = props.fixture[fixtureKey];
            this.newFixture = handlers
                ? this.getNewFixture(props.fixture, handlers)
                : props.fixture;
        }

        handleChange(propName, value) {
            if (propName) {
                this.setState({ [propName]: value });
            } else {
                invariant(!_isNil(value) && typeof value === 'object' , 'value must be a valid not empty object, otherwise "propName" must be specified for a handler in fixture');
                this.setState(value);
            }
        }

        getNewFixture(fixture, handlers) {
            const passThoughHandlersProps = handlers.reduce((results, handler) => {
                results[handler.name] = this.handleChange.bind(this, handler.propName);
                return results;
            }, {});

            return {
                ...fixture,
                props: { ...fixture.props, ...passThoughHandlersProps }
            };
        };

        render() {
            const { nextProxy } = this.props;

            return React.createElement(nextProxy.value, {
                ...this.props,
                nextProxy: nextProxy.next(),
                fixture: {...this.newFixture, props: {...this.newFixture.props, ...this.state}}
            });
        }
    }

    return UpdatePropsProxy;
}

```

The fixture, according to your example, will be:

```
// ...inside a fixture file
import { fixtureUpdater } from 'react-cosmos-foo-bar';

export default {
  props: {
    name: 'Denis Fedynich'
  }
  handlers: [{
        name: 'onChange',
        propName: 'value'
    }]
};
```

However this way has a big drawback - props as such don't include handler name. It is defined in handlers section. So, your solution with `fixtureUpdate` seems to be clearer and more scalable for future proposals.

You mentioned about some done groundwork for the idea to handle stateless components. Nice to hear, so I will leave aside with my quick implementation and will be looking forward to turning your `fixtureUpdate` solution into a new proxy.

**Comment by skidding** [comment] 2017-09-08 15:12
> You mentioned about some done groundwork for the idea to handle stateless components. Nice to hear, so I will leave aside with my quick implementation and will be looking forward when you turn your fixtureUpdate solution into a new proxy.

I must've communicated poorly. There was no work done, just some discussions. I was emphasizing that I like the idea.

Thanks for coming up with an example already. Comments:

- No need to store the updated fixture in the proxy. The Loader already handles the fixture state. All you have to do is call `props.onFixtureUpdate({ props: newProps })` in any proxy and the state will be updated and it will trickle down back into the proxy that originated it – stateless style :)
- Keeping separate `handlers` adds to the Cosmos [DSL](https://en.wikipedia.org/wiki/Domain-specific_language), and fixtures + proxies is already a lot to chew for most people. I'm thinking of something like this:

```js
export default {
  props: {
    name: 'Denis Fedynich',
    onChange: {
       __PROP_UPDATER__: true
      handler: (props, name) => ({
        ...props,
        name,
      })
    }
  }
};
```

Of course we don't want to have ugly fixtures, so a propUpdater helper would come in handy.

```js
// Use a nice helper
const propUpdater = handler => ({
  __PROP_UPDATER__: true,
  handler
});

// Then we can write pretty fixtures
export default {
  props: {
    name: 'Denis Fedynich',
    onChange: propUpdater((props, name) => ({
      ...props,
      name
    }))
  }
};
```

Then the proxy intercepts all props that are objects with `__PROP_UPDATER__` property and override them like this:

```js
const { onChange } = fixture.props;
fixture.onChange = name => {
  const newProps = onChange.handler(fixture.props, name);
  onFixtureUpdate({ props: newProps });
};
```

PS. I reduced my example to just updating props (like your initial example) for now because I realize it might make things simpler and cover the main use case.

**Comment by dfedynich** [comment] 2017-09-11 15:32
I tried to implement the proxy in the way, that you suggested. But I couldn't send fixture update because of parent DOMException: `Failed to execute 'postMessage' on 'Window`'. This error makes sense because there are some handlers in props, which are not serializable in JSON. So, do we have a chance to include any handlers in props and pass them in onFixtureUpdate method finally? As far as I understand this method tries to serialize props and stop execution if serialization fails.

Here is the helper, as you suggested:
```
export default function propUpdater(handler) {
    return {
        __PROP_UPDATER__: true,
        handler
    }
}
```

Here is the fixture
```
export default {
    props: {
        name: 'John Doe',
        onChange: propUpdater((props, name) => ({
            ...props,
            name
        })),
    }
```

And here is the attempt to implement the proxy in the way, that you suggested:
```
import React from 'react';
import _reduce from 'lodash/reduce';

const defaults = {
    fixtureHandlerKey: 'handler',
    fixtureMetaKey: '__PROP_UPDATER__'
};

export default function updatePropsProxy(options) {
    const { fixtureMetaKey, fixtureHandlerKey } = { ...defaults, ...options };

    class UpdatePropsProxy extends React.PureComponent {
        constructor(props) {
            super(props);

            this.getUpdatePropHandler = this.getUpdatePropHandler.bind(this);

            const handlers = _reduce(props.fixture.props, (results, propValue, propName) => {
                if (propValue[fixtureMetaKey] && propValue[fixtureHandlerKey]) {
                    results[propName] = this.getUpdatePropHandler(propValue[fixtureHandlerKey]);
                }
                return results;
            }, {});

            this.newFixture = {
                ...props.fixture,
                props: { ...props.fixture.props, ...handlers }
            };
        }

        getUpdatePropHandler(propHandler) {
            return (handlerValue) => {
                const newProps = propHandler(this.newFixture.props, handlerValue);
                this.props.onFixtureUpdate({ props: newProps });
            }
        }

        render() {
            const { nextProxy } = this.props;
            return React.createElement(nextProxy.value, {
                ...this.props,
                nextProxy: nextProxy.next(),
                fixture: this.newFixture
            });
        }
    }

    return UpdatePropsProxy;
}
```

When `onChange` method is executed, I get the next exception:
![image](https://user-images.githubusercontent.com/7403902/30282808-0d49bd92-971f-11e7-89a6-34e592cdf3ca.png)

Is there any way to resolve it? Where did I mistake?

**Comment by skidding** [comment] 2017-09-11 20:32
> Where did I mistake?

No mistake! Your solution is good!

The problem is we can't send non serializable values from Loader to Playground, so the editor won't update. But, before we find a solution for that (I'm thinking*), does the fixture update in the Loader? Does the component receive the updated props? That's the essential part.

\* The solutions is probably this: Only send the serializable props (we already have a lib for splitting a fixture in unserializable & serializable parts), and in the Playground merge the props by adding the ones received with the previous unserializable props.

**Comment by skidding** [comment] 2018-03-28 15:09
There's been recent interest about this on Slack, so here's an update on how we could achieve this. @dfedynich's solution was good, but it was working around Cosmos, because currenty there's no proxy API for updating a fixture and triggering a re-mount, only for signaling an update which should mirror some internal state change that already happened, like a Redux action dispatched organically. This might sound confusing, but I'll try to clarify with some concrete references.

- The enzyme context wrapper already has `set` and `setProps` methods, which allow us to mutate a loaded fixture, but only with the Enzyme Test API. See [here](https://github.com/react-cosmos/react-cosmos/blob/58bcd54e28a3e151813b9ef49e120a88bb2fbc2f/packages/react-cosmos-test/src/enzyme.js#L64-L84)
- We need to add these methods to the low-level `createContext` API, which is at the base of both the Playground UI and the Test APIs. It would go [here](https://github.com/react-cosmos/react-cosmos/blob/58bcd54e28a3e151813b9ef49e120a88bb2fbc2f/packages/react-cosmos-loader/src/create-context.js#L68).
- Then we need to map this function to a proxy prop like `setFixtureField`. [Here](https://github.com/react-cosmos/react-cosmos/blob/58bcd54e28a3e151813b9ef49e120a88bb2fbc2f/packages/react-cosmos-loader/src/create-context.js#L99).

Once we nail this part, writing the proxy should be straightforward, especially with all the context in this thread. Anybody want to lead this effort?

**Comment by raycar5** [comment] 2018-03-29 07:52
I can give it a try in a few days

**Comment by omarzion** [comment] 2018-11-23 00:18
I ran into a similar issue and came up with a possible solution.  Do you think this would be worth turning into a proxy?
```
// utils.js
import React from 'react';

export default Component => props => (
  <Wrapper {...props} Child={Component} />
)

class Wrapper extends React.Component {
  constructor(props) {
    super(props);
    this.state = Object.keys(props.__controllers).map(key => (
      { [key]: (...args) => this.setState(props.__controllers[key](...args)) }
    )).reduce((acc, cur) => ({...acc, ...cur }), {});
  }

  render() {
    const { Child, __controllers, ...rest} = this.props;
    let props = {...rest, ...this.state};
    return <Child {...props}/>
  }
}
```

And using it (it currently uses __controllers prop)
```
import React from 'react';
import Wrap from './utils';


const Input = props => <input {...props} />

export default {
  component: Wrap(Input),
  props: {
    value: '',
    __controllers : {
      onChange: e => ({ value: e.target.value })
    }
  }
}
```

**Comment by skidding** [comment] 2018-11-25 21:14
@omarzion Looks great! Alternatively, you could put `__controllers` outside props? Eg.

```js
export default {
  component: Wrap(Input),
  props: {
    value: ''
  },
  controllers: {
    onChange: e => ({ value: e.target.value })
  }
}
```

Also, you may want to pass previous props to controller functions (as 1st arg), as you would to a reducer. Eg.

```js
export default {
  component: Wrap(Input),
  props: {
    value: ''
  },
  controllers: {
    onChange: (prevProps, e) => ({ ...prevProps, value: e.target.value })
  }
}
```

> Do you think this would be worth turning into a proxy?

I think so. It's a good solution for the problem discussed in this thread. If you publish a proxy I'll link to it in the docs. But note that I plan to introduce a new API for proxies, probably next month. So it's up to you to decide if you want to invest into publishing this. That said, migration to the new APIs will take longer so it might still be valuable for others to reuse your proxy in the meantime.

**Comment by skidding** [comment] 2018-11-28 08:32
> I got it working as a basic proxy.
> https://www.npmjs.com/package/react-cosmos-stateful-proxy

Cool. Feel free to send a PR to add it to [this list](https://github.com/react-cosmos/react-cosmos#more-proxies).

> I'm not sure where to begin with getting it to update the editor.

You have to call `onFixtureUpdate` from the proxy's props. See [this example](https://github.com/react-cosmos/react-cosmos/blob/65889fc3d1e5fd9779381c037879b4c14c520799/packages/react-cosmos-router-proxy/src/index.js#L25-L27) from the router proxy.

**Comment by skidding** [comment] 2018-11-30 08:34
@dfedynich What do you think of [@omarzion's proxy](https://github.com/omarzion/react-cosmos-stateful-proxy), can we close this issue?

**Comment by skidding** [comment] 2018-12-03 09:46
Great!

**Closed by skidding** 2018-12-03 09:46 UTC
Labels: i have a dream, needs love

**Comment by skidding** [comment] 2019-05-13 14:33
To people who were interested in this thread: Check out [Function fixtures](https://github.com/react-cosmos/react-cosmos/blob/2a9addb0d0824d00d79e654ec5696b8ebbb68638/NEXT.md#function-fixtures), the latest addition to Cosmos Next that addresses the same need in the simplest way possible.
