### ISSUE TITLE
How to rename fixtures with cosmos/next and graphql proxy

### ISSUE THREAD

**Issue by tomitrescak** [react-cosmos/react-cosmos#924] opened 2019-02-04 09:20 UTC
### What's up?

FANTASTIC work! I love this and giving a go to the next version.
I have couple questions.

1. How to specify fixture name and namespace in the "next" version?
2. I absolutely LOVE the graphql proxy. Will this work with the Next version?

Thanks

**Comment by skidding** [comment] 2019-02-05 17:36
Hi @tomitrescak,

Thanks! 🙏

1. Not possible yet. Could you help me understand your use case? I’m gathering info for deciding on the next batch of features to add in Cosmos Next.
2. It’s not directly portable, but I’d say 80-90% of the Apollo proxy code is portable so we just need to adapt it to the new fixture format going forward. Note that I won’t push Cosmos Next as the primary Cosmos version until we have ported the main 3rd party plugins (like the Apollo proxy).

**Comment by tomitrescak** [comment] 2019-02-05 21:39
@skidding as per 1) it's just for the nicer organisation of my fixtures to give them different, more expressive names. For example, when I export three fixtures from the same file each of them can represent a different state of the component. It would be nice to explicitly say this. For example:

1. Component With Error
2. Component Loading
3. Component Loaded Single Entry ...

As per 2, awesome! The Apollo integration is state of the art here. Renders all other approaches just a pain in the a$$ ;) Trust me, I tried them all ;)

**Comment by skidding** [comment] 2019-02-09 21:50
> For example, when I export three fixtures from the same file each of them can represent a different state of the component.

You know what, I've been thinking about this lately too and now that you mention it I'm strongly considering adding this functionality in the next batch of Cosmos Next features.

How about this: Besides being able to export a fixture (ie. a JSX element) from  a fixture file, you can also export a dictionary with multiple fixtures and the key for each fixture in the dictionary becomes the name of its corresponding fixture in the tree view. This means that a _multiple fixtures file_ will look like a folder in the UI.

Eg.

```js
// myfixture.js
export default {
  'Component With Error': <MyComponent ... />,
  'Component Loading': <MyComponent ... />,
  'Component Loaded Single Entry': <MyComponent ... />
}
```

> `myfixture` will become a dir with three items in the tree view.

What do you think? Does this solve your needs?

---

Initially I wanted to tackle this problem by allowing named exports in fixture files, where the name of the export becomes the name of the fixture. The named export solution is more elegant I think. But I now believe that the solution above has three advantages:

- It's easier to implement. Handling named exports requires separate heuristics between ES6 and ES5 modules.
- Named exports can't contain spaces (and probably other chars that you can put in an object key).
- Putting all fixtures in a single exports leaves the opportunity for a feature that I don't know if we're ever going to pursue, but it sounds cool so nice not to rule it out: Allow fixtures exported from files that also contain the source code. Eg. A button component with usage examples in the same file. Someone suggested this on Slack and I made the connection with this thread. Again, not planning to go in that direction but I like that this solution doesn't close that opportunity.

Happy to hear any other thoughts on this!

**Comment by tomitrescak** [comment] 2019-02-11 00:38
Hi, seems like a good ides, but I do not it will scale much. If you will decide to make richer API in the future you will be limited. I created a similar system to COSMOS (by FAR less popular :) and what worked for me was exporting more complex information. Of course you can support all three, should be fairly straightforward:

```js
// first type
export default <MyComponent />

// second type
export default {
  'Component With Error': <MyComponent ... />,
  'Component Loading': <MyComponent ... />,
  'Component Loaded Single Entry': <MyComponent ... />
}

// third type
// myfixture.js
export default [
  {
    name: 'Component With Error',
    component: <MyComponent ... />,
    other API props
  }
]
```

**Comment by skidding** [comment] 2019-02-11 07:38
The third type is very close to how Cosmos works in the stable version. The reason I'm moving away from that is because it's less natural than writing JSX, and you can put the "other API props" in decorators around the component. See https://github.com/skidding/react-mock. The disadvantage to JSX is the additional nesting every layer adds, but it has other advantages like type safety.

**Comment by skidding** [comment] 2019-05-06 16:10
Closing this because multi fixtures now allow custom fixture names. Other than that fixtures are file system-driven by design. There's no GraphQL decorator for Cosmos Next yet, feel free to start a separate thread for that.

**Closed by skidding** 2019-05-06 16:10 UTC
