### ISSUE TITLE
"Error: Already listening" with create-react-app 4.0.0

### ISSUE THREAD

**Issue by AlexFlasch** [react-cosmos/react-cosmos#1272] opened 2020-10-29 22:05 UTC
## What's wrong?

I've just started a project using CRA 4.0.0 and intended to use react-cosmos. Switching to using the `cosmos.config.json` recommended for CRA projects causes a React error overlay stating "Error: Already listening" with a stack trace that seems to point to React Refresh being involved?

This could be related to #1150 since CRA 4.0.0 has officially moved to React Refresh.

## Steps to reproduce

1.  Create a new CRA project with the base template (make sure to use the latest CRA version) `npx create-react-app cra-4-error`

2.  Add a `cosmos.config.json` with the following contents:
```
{
  "staticPath": "public",
  "watchDirs": ["src"],
  "webpack": {
    "configPath": "react-scripts/config/webpack.config"
  }
}
```
(the same as recommended in the Create React App section of the docs)

3.  Run `cosmos` and the error "Error: Already listening" should appear on the page.

## Screenshots

<img width="1680" alt="Screen Shot 2020-10-29 at 4 49 37 PM" src="https://user-images.githubusercontent.com/2762315/97636485-6a3d8d00-19f6-11eb-96e4-7cb660cebcd2.png">

### Server terminal output

no terminal error output

### Browser console output

<details>
<summary>output</summary>

```
Uncaught Error: Already listening
    at Module.ae (index.js:1)
    at Object.init (reactErrorOverlay.js:22)
    at Object../node_modules/react-cosmos/dist/plugins/webpack/client/errorOverlay/index.js (index.js:9)
    at __webpack_require__ (bootstrap:851)
    at fn (bootstrap:150)
    at Object../node_modules/react-cosmos/dist/plugins/webpack/client/index.js (index.js:15)
    at __webpack_require__ (bootstrap:851)
    at fn (bootstrap:150)
    at Object.<anonymous> (main.js:13)
    at __webpack_require__ (bootstrap:851)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.js:1

WebSocket connection to 'ws://localhost:5000/sockjs-node' failed: Connection closed before receiving a handshake response
```

</details>

### Cosmos version

react-cosmos@5.5.1

### If bug occurred on upgrade: Working Cosmos version

n/a

### Cosmos config

```
{
  "staticPath": "public",
  "watchDirs": ["src"],
  "webpack": {
    "configPath": "react-scripts/config/webpack.config"
  }
}
```

### If applicable: webpack version

webpack@4.44.2

#### If applicable: webpack config

points to react-scripts@4.0.0's webpack config

**Comment by AlexFlasch** [comment] 2020-10-30 14:58
I've discovered that react-styleguidist seems to be having very similar issues with CRA 4.0.0

They've [mentioned a workaround on this issue.](https://github.com/styleguidist/react-styleguidist/issues/1705#issuecomment-719546630)

For now this workaround appears to just fall back on the old hot reload plugin CRA used before 4.0.0.

I have tried this on my project and it does indeed work.

## Workaround steps

1. `npm install --save-dev cross-env` or `yarn add --dev cross-env`
1. Modify your `cosmos` npm script to `"cross-env FAST_REFRESH=false cosmos"`
1. Run `npm run cosmos` or `yarn cosmos`

**Comment by skidding** [comment] 2020-11-01 01:03
@AlexFlasch Thanks for sharing your findings!

I'll keep this issue open for future reference and it case anyone finds a solution for integrating Fast Refresh into Cosmos – I don't really know what the issue is because I haven't had time to research, but it would be of great help if anybody did.

**Comment by AlexFlasch** [comment] 2020-11-01 01:23
No problem! I'll do some digging on react-refresh and what might be causing the error. No promises though, as I'm far from a webpack expert. 😅

**Comment by skidding** [comment] 2020-11-24 16:29
Spent some time today digging into this. For now, the only solution is to set `FAST_REFRESH=false` when running Cosmos as @AlexFlasch suggested [above](https://github.com/react-cosmos/react-cosmos/issues/1272#issuecomment-719602862).

As for how to bring Fast Refresh and Cosmos, here are my findings.

For some context:

- Create React App uses [webpack-dev-server](https://github.com/webpack/webpack-dev-server) to take care of its dev server needs. It's configured [here](https://github.com/facebook/create-react-app/blob/f5c3bdb65480f93b2d4a4c2f3214fc50753de434/packages/react-scripts/config/webpackDevServer.config.js). This is nice for CRA as it uses as much as possible from the webpack ecosystem. One of the benefits of using WDS is the [built-in socket connection](https://github.com/webpack/webpack-dev-server/blob/89ffb86cd26425c59e3937ca06a2c804a01b8f1d/lib/Server.js#L696-L757). That said, CRA does implement [its own dev server client](https://github.com/facebook/create-react-app/blob/de8b2b3f2d0a699284420c19d5b4db0be776e0cf/packages/react-dev-utils/webpackHotDevClient.js), which maintains the socket connection and includes the iconic CRA error overlay. The default WDS client is disabled [here](https://github.com/facebook/create-react-app/blob/de8b2b3f2d0a699284420c19d5b4db0be776e0cf/packages/react-scripts/config/webpackDevServer.config.js#L77-L79).
- Cosmos, on the other hand, assembles the webpack dev server using lower level primitives: [weback-dev-middleware](https://github.com/webpack/webpack-dev-middleware) and [webpack-hot-middleware](https://github.com/webpack-contrib/webpack-hot-middleware). The former is used internally by WDS, but the latter isn't. In fact, WHM hasn't been updated since May 15, 2019, and likely needs to be replaced in Cosmos to move forward with this issue.
- WHM uses EventSource to send server messages to the browser client. This didn't matter until now, because WHM includes both a server middleware and a browser [client](https://github.com/webpack-contrib/webpack-hot-middleware/blob/master/client.js), and Cosmos uses both when `webpack.hotReload` is enabled (on by default). CRA's Fast Refresh-enabled [client](https://github.com/facebook/create-react-app/blob/de8b2b3f2d0a699284420c19d5b4db0be776e0cf/packages/react-dev-utils/webpackHotDevClient.js), however, uses WebSocket to communicate with the server.

I'm not sure what the best course of action is yet, but here are some options:

For the client:

1. Piggy-back on CRA and import its own client from `react-dev-utils/webpackHotDevClient`. The drawback is Fast Refresh won't be available for non-CRA Cosmos users.
2. Copy the essential parts from CRA's client into the Cosmos codebase. Depending on the server-side solution, this means A) change the WebSocket connection to EventSource (unless two-way communication is needed, which the latter doesn't support) or B) keep the WebSocket connection and expect the server to expose a WebSocket connection.

For the sever:

1. Keep webpack-hot-middleware. This works with client option 2A. This only works if the Fast Refresh doesn't depend on newer messages that might be included in WDS but not backported in WHM.
2. Use webpack-dev-server in Cosmos. This would remove some code from the Cosmos codebase, but requires more work. We could rely on the user's installed WDS dependency, as we do for webpack already. The problem is that Cosmos' server is more than just a webpack server. So there are two sub-options here: A) Use WDS' [before](https://webpack.js.org/configuration/dev-server/#devserverbefore) and [after](https://webpack.js.org/configuration/dev-server/#devserverafter) options to extend the the underlying Express app with Cosmos endpoints. I'm not even sure if I want to consider this because webpack is a Cosmos plugin, not the other way around. B) Start two servers on two ports: One for Cosmos stuff and one for webpack stuff. The Cosmos server, which serves the Playground URL would have to run on the main port, and the webpack server, which serves the renderer iframe URL, would run on a secondary port. Communicating between different ports with postMessage might require additional changes, and an additional Cosmos config option would be required to customize the renderer port.
3. Copy the essential parts from [WDS' socket connection](https://github.com/webpack/webpack-dev-server/blob/89ffb86cd26425c59e3937ca06a2c804a01b8f1d/lib/Server.js#L696-L757) into the Cosmos codebase, which would in turn replace the current use of webpack-hot-middleware. This gives us control, but isn't trivial. `sockWrite` is called all over the place across the 1000-lines Server.js file. Copy pasting a library without understanding it is a red flag, and WDS can easily become a moving target.

This needs more thought, but at the moment I'm inclined to favor option client option 2B with server option 2B. The client would be copy pasted and maintained in the Cosmos codebase, but it's manageable at 280 lines and this would enable Fast Refresh and the error overlay to non-CRA Cosmos users. The server would be rid of both webpack-dev-middleware and webpack-hot-middleware. Instead, Cosmos would rely on user's version of webpack-dev-server, making it more robust to changes. But the implications of opening two servers on two ports that speak two each other needs to be further investigated, along with the implications for the static export.

Finally, before committing to any solution, we need to also investigate how compatible is the chosen solution with Next users, as well as people with custom setups.

As always, integrating with various webpack setups seamlessly is a hairy business. This is the cross this project has to bear. Congrats if you've read this far, especially if all this makes sense. and definitely lend me a hand if you're able to. Thanks!

**Comment by AlexFlasch** [comment] 2020-11-24 17:10
That's a great write-up on the issue! If I have some bandwidth in the coming weeks/months I'd be happy to try and help, but I would likely need some guidance as I only have surface level familiarity with webpack.

I had played around a bit with the PR I opened to try and fix this issue, but I couldn't find a simple solution to fix it, and this write-up definitely explains why there's no easy fix!

With the extra info provided here, I'll close my PR as it was aiming to apply a simple fix by adding `react-refresh` as a dependency within the project.

**Comment by skidding** [comment] 2020-11-24 21:42
Here's a rough issue breakdown based on the ideas above.

### Step 1: Integrate webpack-dev-server

The main thing that needs to be validated is whether that Cosmos should migrate to webpack-dev-server from the current webpack-dev-middleware + webpack-hot-middleware solution.

The reasons for this are to:

1. Align the webpack architecture in Cosmos with the one from CRA to enable Fast Refresh in Cosmos. Not just for CRA users, but for anyone using Cosmos.
2. Remove some webpack server related code from Cosmos by using a higher level dependency like WDS.
3. Get rid of WDM and WHM (not very up to date) dependencies, and use the version of WDS installed by the user.

The main implication is this: At the moment Cosmos runs a single Express app on a port (default 5000) that serves both Cosmos and webpack endpoints. With this change, the webpack dev server will run on a separate port from the primary Cosmos server.

On to the implementation. All webpack related code is in [packages/react-cosmos/src/plugins/webpack](https://github.com/react-cosmos/react-cosmos/tree/e92f1ecbce529af4b4706172b7e5aae15823ff1e/packages/react-cosmos/src/plugins/webpack).

This is where webpack-dev-middleware is used: https://github.com/react-cosmos/react-cosmos/blob/e92f1ecbce529af4b4706172b7e5aae15823ff1e/packages/react-cosmos/src/plugins/webpack/devServer.ts#L93-L101

This is where where webpack-hot-middleware is used:
https://github.com/react-cosmos/react-cosmos/blob/e92f1ecbce529af4b4706172b7e5aae15823ff1e/packages/react-cosmos/src/plugins/webpack/devServer.ts#L103-L106

The renderer URL needs to be adjusted to point to the port of the new webpack server. Here:
https://github.com/react-cosmos/react-cosmos/blob/59011fbd22d7eda6ebeb071fecc0b445c7789a6c/packages/react-cosmos/src/shared/playgroundHtml.ts#L91-L93

The important thing here is that the renderer URL will point to `http://localhost:5001/_renderer.html` in dev mode, but still point to `/_renderer.html` in a static export where all files are pre-generated.

And also here:
https://github.com/react-cosmos/react-cosmos/blob/e92f1ecbce529af4b4706172b7e5aae15823ff1e/packages/react-cosmos/src/getFixtures2.ts#L87-L93

### Step 2: Preparing the next release

There are a bunch of tasks to be done if the first step is validated:

- [ ] Copy Create React App's [dev client](https://github.com/facebook/create-react-app/blob/de8b2b3f2d0a699284420c19d5b4db0be776e0cf/packages/react-dev-utils/webpackHotDevClient.js) with Fast Refresh support
  - [ ] Clean up duplicate [error overlay code](https://github.com/react-cosmos/react-cosmos/blob/e92f1ecbce529af4b4706172b7e5aae15823ff1e/packages/react-cosmos/src/plugins/webpack/client/errorOverlay/reactErrorOverlay.ts).
- [ ] Adjust static exporting as needed.
- [ ] Add `webpack.port` config option for customizing the port of the webpack server.
- [ ] Potentially: Add `webpack.devServerConfig` config option, similar to `webpack.config`, for customizing the options passed to the dev server. It might also even be possible for CRA users to set the value to [`react-scripts/config/webpackDevServer.config`](https://github.com/facebook/create-react-app/blob/de8b2b3f2d0a699284420c19d5b4db0be776e0cf/packages/react-scripts/config/webpackDevServer.config.js) and integrate seamlessly.

Anyone who wants to take a stab at this is welcome. For direct messaging find me on [Slack](https://react-cosmos.slack.com/join/shared_invite/zt-g9rsalqq-clCoV7DWttVvzO5FAAmVAw#/).

Also a side quest: Link command for Cosmos contributors #1276

**Comment by skidding** [comment] 2023-04-19 18:18
This was already fixed in https://github.com/react-cosmos/react-cosmos/pull/1352.

Linked the comments about refactoring the webpack integration in the roadmap for future reference.

**Closed by skidding** 2023-04-19 18:18 UTC
