### ISSUE TITLE
Handle in-tree test files

### ISSUE THREAD

**Issue by NLincoln** [react-cosmos/react-cosmos#444] opened 2017-09-14 22:04 UTC
My app has it's test file in-tree, right alongside the component files. Like this:
```
src
├── components
│   ├── Select
│   │   ├── index.js
│   │   ├── Select.js
│   │   └── Select.spec.js
```
`react-cosmos` outputs several errors because of this:

#### Webpack building errors:
There are numerous errors, but they all follow this form:
```
cosmos_1    | 
cosmos_1    | ERROR in ./node_modules/enzyme/build/react-compat.js
cosmos_1    | Module not found: Error: Can't resolve 'react/lib/ReactContext' in '/app/node_modules/enzyme/build'
cosmos_1    |  @ ./node_modules/enzyme/build/react-compat.js 42:21-54
cosmos_1    |  @ ./node_modules/enzyme/build/ReactWrapper.js
cosmos_1    |  @ ./node_modules/enzyme/build/index.js
cosmos_1    |  @ ./src/components/query-component/QueryComponent.spec.js
cosmos_1    |  @ ./src/components/query-component nonrecursive \.jsx?$
cosmos_1    |  @ ./node_modules/react-cosmos-webpack/lib/user-modules.js
cosmos_1    |  @ ./node_modules/react-cosmos-webpack/lib/loader-entry.js
cosmos_1    |  @ multi (webpack)-hot-middleware/client.js?reload=true ./node_modules/react-cosmos-webpack/lib/loader-entry.j
```
(the `cosmos_1 | ` prefix to everything is because it's running inside docker-compose and can be ignored)

But wait! it still builds and I can see my components in the browser! 
After creating some fixture files, I see this: 
![screenshot_20170914_170240](https://user-images.githubusercontent.com/2380692/30457814-880e515e-996e-11e7-9a4b-0f94a9ea1054.png)

Unfortunately, clicking on the `default` button gives this mess of errors:
![screenshot_20170914_170316](https://user-images.githubusercontent.com/2380692/30457842-a01c6876-996e-11e7-8f85-b36c2d7e9ab1.png)

### Solution?

Based on my (limited!) webpack knowledge, I assume that cosmos is trying to build my test files and treating them as components. I'm pretty sure that ignoring all files that end in `(spec|test).js` would probably fit the bill.

**Comment by skidding** [comment] 2017-09-14 22:16
Indeed this is annoying. Ignoring standard test files [by default](https://github.com/react-cosmos/react-cosmos/blob/master/packages/react-cosmos-config/src/index.js#L12) is a good idea!

**Comment by NLincoln** [comment] 2017-09-14 22:27
I added 
```js
  ignore: [
    /(.*)\.spec$/
  ]
```
to my config, but now the console is emitting this error:
![screenshot_20170914_172704](https://user-images.githubusercontent.com/2380692/30458606-eef0494c-9971-11e7-9168-59fa22b1a1e8.png)

**Comment by skidding** [comment] 2017-09-14 22:29
It seems like the file is still included. How about `/\.spec.js$/`?

**Comment by NLincoln** [comment] 2017-09-14 22:29
Ninja edited, I had that in there in the first place :sweat_smile:

**Comment by skidding** [comment] 2017-09-14 22:31
And does it work now? You can just try `/spec/` to begin with, to see if it's not a bug with how Cosmos ignores files.

**Comment by rohannair** [comment] 2017-09-20 15:20
So I'm trying this as well, and the ignoring does not work properly. 

## cosmos.config.js
```javascript
module.exports = {
  componentPaths: ['src/components'],
  containerQuerySelector: '#root',
  webpackConfigPath: 'react-scripts/config/webpack.config.dev',
  publicPath: 'public',
  ignore: [
    /\.test\.js$/
  ]
}

```

**Comment by skidding** [comment] 2017-09-20 16:43
OK, sounds like a bug. It would be great if anyone can look into this and find a fix before we end the release candidate period for 2.0.

**Comment by skidding** [comment] 2017-10-24 19:35
Closing this because in v3 only components with fixtures show up in the playground. See [Cosmos v3 BETA TESTING thread](https://github.com/react-cosmos/react-cosmos/issues/475).

**Closed by skidding** 2017-10-24 19:35 UTC
Labels: free for all, oops
