### ISSUE TITLE
Does not work in neutrinojs setup

### ISSUE THREAD

**Issue by dantman** [react-cosmos/react-cosmos#1045] opened 2019-09-21 23:44 UTC
### What's wrong?

I am trying to setup react cosmos in my neutrinojs based project. However it just sits there saying "Waiting for renderer..." with nothing on the left and an image below.

I did a little investigation and it looks like it loads _renderer.html but what comes back is my normal index.html's contents.

I cannot find any documentation on configuration I may need to change.

### Steps to reproduce

1. Use a [neutrinojs 9](https://master.neutrinojs.org/) based webpack config
2. Use `@neutrinojs/react` with an ejs template

### Screenshots

<img width="1063" alt="Screen Shot 2019-09-21 at 4 35 17 PM" src="https://user-images.githubusercontent.com/53399/65380319-d5624f00-dc8d-11e9-81de-15996e09950a.png">

### User info

- No errors in terminal output
- Nothing in browser console
- Cosmos 5.0.0-beta.3
- Cosmos config
  ```json
  {
    "$schema": "http://json.schemastore.org/cosmos-config",
    "port": 3001,
    "watchDirs": ["src"],
    "fixturesDir": "src/__fixtures__",
    "webpack": {
      "configPath": "webpack.config.js"
    }
  }
  ```
- WebPack 4.28.3
- <details> 
  <summary>WebPack config</summary>
  
  ```js
  {
    target: 'web',
    context: '{...}',
    stats: {
      children: false,
      entrypoints: false,
      modules: false
    },
    node: {
      Buffer: false,
      fs: 'empty',
      tls: 'empty'
    },
    output: {
      path: '{...}/build',
      publicPath: '/',
      filename: 'assets/[name].[contenthash:8].js',
      crossOriginLoading: 'anonymous'
    },
    resolve: {
      alias: {
        'react-native': 'react-native-web'
      },
      extensions: [
        '.js',
        '.tsx',
        '.coffee',
        '.web.jsx',
        '.web.js',
        '.wasm',
        '.mjs',
        '.jsx',
        '.json'
      ]
    },
    module: {
      rules: [
        /* neutrino.config.module.rule('html') */
        {
          test: /\.html$/,
          use: [
            /* neutrino.config.module.rule('html').use('html') */
            {
              loader: '{...}/node_modules/html-loader/index.js',
              options: {
                attrs: [
                  'img:src',
                  'link:href'
                ]
              }
            }
          ]
        },
        /* neutrino.config.module.rule('compile') */
        {
          test: /\.(mjs|jsx|js)$/,
          include: [
            '{...}/src',
            '{...}/test'
          ],
          use: [
            /* neutrino.config.module.rule('compile').use('babel') */
            {
              loader: '{...}/node_modules/babel-loader/lib/index.js',
              options: {
                cacheDirectory: true,
                babelrc: false,
                configFile: false,
                presets: [
                  [
                    '{...}/node_modules/@babel/preset-env/lib/index.js',
                    {
                      debug: false,
                      useBuiltIns: 'entry',
                      targets: {}
                    }
                  ],
                  [
                    '{...}/node_modules/@babel/preset-react/lib/index.js',
                    {
                      development: false,
                      useBuiltIns: true
                    }
                  ]
                ],
                plugins: [
                  '{...}/node_modules/@babel/plugin-syntax-dynamic-import/lib/index.js',
                  '{...}/node_modules/react-hot-loader/babel.js',
                  [
                    '{...}/node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js',
                    {
                      removeImport: true
                    }
                  ],
                  [
                    '{...}/node_modules/@babel/plugin-proposal-class-properties/lib/index.js',
                    {
                      loose: true
                    }
                  ]
                ]
              }
            }
          ]
        },
        /* neutrino.config.module.rule('style') */
        {
          test: /\.css$/,
          exclude: [
            /\.module\.css$/
          ],
          use: [
            /* neutrino.config.module.rule('style').use('extract') */
            {
              loader: '{...}/node_modules/mini-css-extract-plugin/dist/loader.js'
            },
            /* neutrino.config.module.rule('style').use('css') */
            {
              loader: '{...}/node_modules/css-loader/index.js',
              options: {
                importLoaders: 0
              }
            }
          ]
        },
        /* neutrino.config.module.rule('style-modules') */
        {
          test: /\.module\.css$/,
          use: [
            /* neutrino.config.module.rule('style-modules').use('extract-modules') */
            {
              loader: '{...}/node_modules/mini-css-extract-plugin/dist/loader.js'
            },
            /* neutrino.config.module.rule('style-modules').use('css-modules') */
            {
              loader: '{...}/node_modules/css-loader/index.js',
              options: {
                importLoaders: 0,
                modules: true
              }
            }
          ]
        },
        /* neutrino.config.module.rule('font') */
        {
          test: /\.(eot|ttf|woff|woff2)(\?v=\d+\.\d+\.\d+)?$/,
          use: [
            /* neutrino.config.module.rule('font').use('file') */
            {
              loader: '{...}/node_modules/file-loader/dist/cjs.js',
              options: {
                name: 'assets/[name].[hash:8].[ext]'
              }
            }
          ]
        },
        /* neutrino.config.module.rule('image') */
        {
          test: /\.(ico|png|jpg|jpeg|gif|svg|webp)(\?v=\d+\.\d+\.\d+)?$/,
          use: [
            /* neutrino.config.module.rule('image').use('url') */
            {
              loader: '{...}/node_modules/url-loader/dist/cjs.js',
              options: {
                limit: 8192,
                name: 'assets/[name].[hash:8].[ext]'
              }
            }
          ]
        },
        /* neutrino.config.module.rule('compile-packages') */
        {
          parser: {
            amd: false
          },
          test: /\.(mjs|jsx|js)$/,
          include: [
            '{...}/node_modules'
          ]
        },
        /* neutrino.config.module.rule('graphql') */
        {
          test: /\.(graphql|gql)$/,
          use: [
            /* neutrino.config.module.rule('graphql').use('graphql-tag') */
            {
              loader: 'graphql-tag/loader',
              options: {
                exclude: /node_modules/
              }
            }
          ]
        },
        /* neutrino.config.module.rule('sass') */
        {
          test: /.s[ac]ss$/,
          exclude: [
            /\.module\.css$/
          ],
          use: [
            /* neutrino.config.module.rule('sass').use('extract') */
            {
              loader: '{...}/node_modules/mini-css-extract-plugin/dist/loader.js'
            },
            /* neutrino.config.module.rule('sass').use('css') */
            {
              loader: '{...}/node_modules/css-loader/index.js',
              options: {
                importLoaders: 2
              }
            },
            /* neutrino.config.module.rule('sass').use('css-2') */
            {
              loader: 'postcss-loader',
              options: {
                plugins: [
                  function plugin(css, result) {
                      var prefixes = loadPrefixes({
                        from: css.source && css.source.input.file,
                        env: options.env
                      });
                      timeCapsule(result, prefixes);
                  
                      if (options.remove !== false) {
                        prefixes.processor.remove(css, result);
                      }
                  
                      if (options.add !== false) {
                        prefixes.processor.add(css, result);
                      }
                    }
                ]
              }
            },
            /* neutrino.config.module.rule('sass').use('css-3') */
            {
              loader: 'sass-loader'
            }
          ]
        },
        /* neutrino.config.module.rule('sass-modules') */
        {
          test: /\.module\.css$/,
          use: [
            /* neutrino.config.module.rule('sass-modules').use('extract-modules') */
            {
              loader: '{...}/node_modules/mini-css-extract-plugin/dist/loader.js'
            },
            /* neutrino.config.module.rule('sass-modules').use('css-modules') */
            {
              loader: '{...}/node_modules/css-loader/index.js',
              options: {
                importLoaders: 2,
                modules: true
              }
            },
            /* neutrino.config.module.rule('sass-modules').use('css-modules-2') */
            {
              loader: 'postcss-loader',
              options: {
                plugins: [
                  function plugin(css, result) {
                      var prefixes = loadPrefixes({
                        from: css.source && css.source.input.file,
                        env: options.env
                      });
                      timeCapsule(result, prefixes);
                  
                      if (options.remove !== false) {
                        prefixes.processor.remove(css, result);
                      }
                  
                      if (options.add !== false) {
                        prefixes.processor.add(css, result);
                      }
                    }
                ]
              }
            },
            /* neutrino.config.module.rule('sass-modules').use('css-modules-3') */
            {
              loader: 'sass-loader'
            }
          ]
        },
        /* neutrino.config.module.rule('coffee') */
        {
          test: /\.coffee$/,
          include: [
            '{...}/src',
            '{...}/test'
          ],
          use: [
            /* neutrino.config.module.rule('coffee').use('babel') */
            {
              loader: '{...}/node_modules/babel-loader/lib/index.js',
              options: {
                cacheDirectory: true,
                babelrc: false,
                configFile: false,
                presets: [
                  [
                    '{...}/node_modules/@babel/preset-env/lib/index.js',
                    {
                      debug: false,
                      useBuiltIns: 'entry',
                      targets: {}
                    }
                  ],
                  [
                    '{...}/node_modules/@babel/preset-react/lib/index.js',
                    {
                      development: false,
                      useBuiltIns: true
                    }
                  ]
                ],
                plugins: [
                  '{...}/node_modules/@babel/plugin-syntax-dynamic-import/lib/index.js',
                  '{...}/node_modules/react-hot-loader/babel.js',
                  [
                    '{...}/node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js',
                    {
                      removeImport: true
                    }
                  ],
                  [
                    '{...}/node_modules/@babel/plugin-proposal-class-properties/lib/index.js',
                    {
                      loose: true
                    }
                  ]
                ]
              }
            },
            /* neutrino.config.module.rule('coffee').use('coffee') */
            {
              loader: '{...}/node_modules/coffee-loader/index.js'
            }
          ]
        }
      ]
    },
    optimization: {
      minimize: true,
      splitChunks: {
        chunks: 'all',
        maxInitialRequests: 5,
        name: false
      },
      runtimeChunk: 'single'
    },
    plugins: [
      /* neutrino.config.plugin('env') */
      new (require('{...}/node_modules/webpack/lib/EnvironmentPlugin.js'))(
        {
          // ...
        }
      ),
      /* neutrino.config.plugin('html-index') */
      new (require('{...}/node_modules/html-webpack-plugin/index.js'))(
        {
          template: '{...}/src/template.ejs',
          appMountId: 'root',
          lang: 'en',
          meta: {
            viewport: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no'
          },
          filename: 'index.html',
          chunks: [
            'index'
          ],
          title: '...',
          inject: 'head'
        }
      ),
      /* neutrino.config.plugin('extract') */
      new (require('{...}/node_modules/mini-css-extract-plugin/dist/cjs.js'))(
        {
          filename: 'assets/[name].[contenthash:8].css'
        }
      ),
      /* neutrino.config.plugin('clean') */
      new (require('{...}/node_modules/clean-webpack-plugin/index.js'))(
        [
          '{...}/build'
        ],
        {
          root: '{...}',
          verbose: false,
          allowExternal: false,
          dry: false
        }
      ),
      /* neutrino.config.plugin('limit-locales') */
      new IgnorePlugin(
        {
          checkResource: (resource, context) => {
                      const relModule = path.posix.join(
                        ...path
                          .relative(process.cwd(), path.resolve(context, resource))
                          .split(path.sep)
                      );
                      const m = /^node_modules\/cldr-data\/main\/([-\w]+)\/[^/]+\.json$/i.exec(
                        relModule
                      );
                      if (m && !supportedLocales.includes(m[1])) {
                        return true;
                      }
                      return false;
                    }
        }
      ),
      /* neutrino.config.plugin('webapp') */
      new WebappWebpackPlugin(
        {
          logo: './siteicon.png',
          prefix: 'siteicons/',
          favicons: {
            // ...
          }
        }
      ),
      /* neutrino.config.plugin('copy') */
      new (require('{...}/node_modules/copy-webpack-plugin/dist/index.js'))(
        [
          {
            from: 'config/.htaccess',
            to: ''
          },
          {
            context: 'rawimages',
            from: '*.{png,jpg,jpeg}',
            to: 'images'
          },
          {
            from: 'src/legacy/images/',
            to: 'assets/legacy-images/'
          }
        ],
        {
          debug: 'warning'
        }
      ),
      /* neutrino.config.plugin('subresource-integrity') */
      new SubresourceIntegrityPlugin(
        {
          hashFuncNames: [
            'sha256',
            'sha512'
          ],
          enabled: true
        }
      ),
      /* neutrino.config.plugin('imagemin') */
      new ImageminPlugin(
        {
          disable: true,
          test: /\.(jpe?g|png|gif|svg)$/i,
          pngquant: {}
        }
      ),
      /* neutrino.config.plugin('script-ext') */
      new ScriptExtHtmlWebpackPlugin(
        {
          defaultAttribute: 'defer',
          inline: [
            'runtime'
          ]
        }
      )
    ],
    entry: {
      index: [
        '{...}/src/index'
      ]
    }
  }
  ```
  
  </details>

**Comment by dantman** [comment] 2019-09-22 03:48
I did some experimentation, the issue is primarily the template. It appears that react-cosmos does not handle many of the possible ways of configuring HtmlWebpackPlugin.

The problem is [changeHtmlPluginFilename](https://github.com/react-cosmos/react-cosmos/blob/v5.0.0-beta.3/packages/react-cosmos/src/plugins/webpack/webpackConfig/htmlPlugin.ts#L57-L66). If it sees an `index.html` it thinks everything is perfectly fine and doesn't bother modifying the html plugin to fit cosmos' needs. And then even if it gets past that the later constructor doesn't bother removing any options that would break cosmos.

I don't know why you would *not* want to override the plugin filename, even if it was `index.html`. But if there's some reason for that the code needs to take into account the fact that `template` overrides the default template and cosmo's _renderer will not be used if there is a `template`.

Additionally neutrino also specifies the `chunks` option, this option stops the bundles cosmos needs from loading.

So in order for this to work the `template` and `chunks` options need to be omitted from the options that are copied.

I don't know but I'm guessing the `appMountId` might also have some effect on cosmos.

**Comment by dantman** [comment] 2019-09-22 03:50
If that issue is fixed cosmos works. Though as a secondary issue if a fixture has an error the console has a bunch of 404 errors for urls like: `http://localhost:3001/__get-internal-source?fileName=webpack-internal%3A%2F%2F%2F.%2Fnode_modules%2Ftiny-invariant%2Fdist%2Ftiny-invariant.esm.js` suggesting something else is set wrong or not being registered.

**Comment by skidding** [comment] 2019-09-23 20:15
Hi @dantman,

A few ideas before looking more closely into this:

- As a last resort you can use [webpack.overridePath](https://github.com/react-cosmos/react-cosmos#webpack-config-override) to replace the `html-webpack-plugin` with a fresh instance that doesn't break Cosmos. You have to mutate `webpackConfig.plugins` by finding the index of the HTML plugin, which is nasty business, but should allow you to continue until we find a more elegant solution.
-  Maybe the `3001` calls are specific to Neutrino? I can imagine some wrapper that captures errors and expects some backend to communicate with, but this is pure speculation at this point. 
- Could you also provide a reproducing repository that I can clone and debug? I know you've already provided lots of info and I appreciate it! But I'm also low on time these days.

Thank you!

**Comment by dantman** [comment] 2019-09-24 03:31
Here's a test repository: https://github.com/dantman/cosmos-neutrino-test

Using `npx neutrino --inspect` will give you a dump of the webpack config.

master you'll see is broken by the `chunks` option. If you edit `changeHtmlPluginFilename` in `node_modules/react-cosmos/dist/plugins/webpack/webpackConfig/htmlPlugin.js` by commenting out the if condition and adding a `delete htmlPlugin.options.chunks;` to ensure chunks is omitted from the replaced plugin. Then cosmos will start working. Though the error fixture will show you the 404 errors.

If you switch to the template branch you'll see a variant with a template. If you keep the htmlPlugin modification to fix the chunks issue, this will "*work*". However you'll notice it will use the template instead of the normal renderer template. This may or may not be desirable as the template may contain references to 3rd party SDKs that may or may not be relevant in the context of cosmos where SDK initialization may not be present. Which I've represented by adding a google font to the template.

**Comment by skidding** [comment] 2019-09-25 18:25
> Though as a secondary issue if a fixture has an error the console has a bunch of 404 errors for urls like: `http://localhost:3001/__get-internal-source?fileName=webpack-internal%3A%2F%2F%2F.%2Fnode_modules%2Ftiny-invariant%2Fdist%2Ftiny-invariant.esm.js` suggesting something else is set wrong or not being registered.

Here's what I found related to this.

Cosmos uses react-error-overlay (a create-react-app package), which brings the nice CRA error overlay into Cosmos. It's not a perfect marriage, however, because REO is still somewhat coupled to the CRA server.

For example, when you click inside the stack trace, the overlay launches the related file in your editor at the exact column:line. This is also implemented in the Cosmos server.

I've just discovered that there is [another endpoint named `__get-internal-source` that REO sometimes calls](https://github.com/facebook/create-react-app/blob/194a29102f8d777cda593fa52748b3a322bef458/packages/react-error-overlay/src/utils/mapper.js#L38-L40). It is called when the name of the file where the error originated from contains `webpack-internal:`, which [seems to be the byproduct of using a certain class of source map implementations](https://github.com/webpack/webpack/issues/5186#issuecomment-312801144).

Not sure why neutrino uses an eval-based source map implementation, but I've found `cheap-module-source-map` to be a great fit in the past, which is also the default in Cosmos.

There are other many ways to change the `devtool` webpack config, but here's one for your test repo:

```diff
-module.exports = neutrino().webpack();
+module.exports = {
+  ...neutrino().webpack(),
+  devtool: 'cheap-module-source-map'
+};
```

This got rid of the errors. It's not ideal, but unless a better solution becomes obvious I will add a [Troubleshooting](https://github.com/react-cosmos/react-cosmos#troubleshooting) item related to `__get-internal-source` 404s linking to this comment.

---

I'll write a separate response for the HTML webpack plugin situation.

**Comment by skidding** [comment] 2019-09-25 18:45
> The problem is [changeHtmlPluginFilename](https://github.com/react-cosmos/react-cosmos/blob/v5.0.0-beta.3/packages/react-cosmos/src/plugins/webpack/webpackConfig/htmlPlugin.ts#L57-L66). If it sees an `index.html` it thinks everything is perfectly fine and doesn't bother modifying the html plugin to fit cosmos' needs. And then even if it gets past that the later constructor doesn't bother removing any options that would break cosmos.

> I don't know why you would *not* want to override the plugin filename, even if it was `index.html`. But if there's some reason for that the code needs to take into account the fact that `template` overrides the default template and cosmo's _renderer will not be used if there is a `template`.

There are two things to consider about `changeHtmlPluginFilename`:

1. It keeps all instances of HtmlWebpackPlugin that don't have the filename equal to `index.html` as is. I don't remember exactly where this was needed, but some framework or boilerplate was creating multiple assets that were all needed for the components to work properly.
2. It keeps the _main_ HWP instance, but changes its filename to suit the Cosmos architecture. This is the part we're more interested in. I also don't remember where this originated from, but I think you can put a lot of things into html-webpack-plugin options which become run-time dependencies.

> doesn't bother modifying the html plugin to fit cosmos' needs

Don't mean to be too sensitive, but it's hard to "bother" to do everything you'll ever need to do to integrate with other people's webpack configs, including hairy ones generated by frameworks. Let's see if we can do something about it now that we found an issue :).

> This may or may not be desirable as the template may contain references to 3rd party SDKs that may or may not be relevant in the context of cosmos where SDK initialization may not be present. Which I've represented by adding a google font to the template.

In my experience you want to bring as much as possible into the Cosmos runtime. It doesn't seem desirable, but it's needed. Here's a hypothetical yet common use case. There's some global constant in the HTML layout (its value can be hardcoded or computed at build time). Components call some abstraction that reads that global constant internally. Without it a lot of components stop working, making Cosmos less useful.

> If you edit `changeHtmlPluginFilename` in `node_modules/react-cosmos/dist/plugins/webpack/webpackConfig/htmlPlugin.js` by commenting out the if condition and adding a `delete htmlPlugin.options.chunks;` to ensure chunks is omitted from the replaced plugin. Then cosmos will start working.

**This sounds like a plan! Can you see any potential issue with omitting the `chunks` option [here](https://github.com/react-cosmos/react-cosmos/blob/a7288b8a19c9b882965f43146635fb05dab6d973/packages/react-cosmos/src/plugins/webpack/webpackConfig/htmlPlugin.ts#L62-L65)? If not we can turn this into a PR.**

---

PS. I appreciate your time looking into this!

**Comment by dantman** [comment] 2019-09-25 19:07
> This sounds like a plan! Can you see any potential issue with omitting the `chunks` option [here](https://github.com/react-cosmos/react-cosmos/blob/a7288b8a19c9b882965f43146635fb05dab6d973/packages/react-cosmos/src/plugins/webpack/webpackConfig/htmlPlugin.ts#L62-L65)? If not we can turn this into a PR.

That's an ok place to do it. However there are a few things to keep in mind.

1. You may need to use destructuring, an `omit` function, or something else there to literally omit the `chunks` property from `htmlPlugin.options`. I tried "omitting" `template` using `template: undefined`, `template: null`, and `template: ''` and none of them worked. htmlPlugin may be similarly fussy with other options in that the key itself must be omitted to override it.
2. I only tested that things functioned. I did not test the exact effect that deleting `chunks` has. Namely I do not know how cosmos' overriding of loaded scripts works so I don't know if this will have the effect of loading other chunks from the main application (which would be undesirable since my main application is pretty heavy).
3. `if (htmlPlugin.options.filename !== 'index.html') {` also needs to be taken care of (Although I need to re-test this because that `!==` is the opposite of what I thought was my issue). We need some other way to denote what the main html plugin is. Because as long as that condition matches my main html, then it will never reach the part of the code where you omit `chunks` from the options.

**Comment by dantman** [comment] 2019-09-25 20:48
> Not sure why neutrino uses an eval-based source map implementation, but I've found `cheap-module-source-map` to be a great fit in the past, which is also the default in Cosmos.

Probably because [WebPack says](https://webpack.js.org/configuration/devtool/#devtool) they're faster.

**Comment by skidding** [comment] 2019-10-05 09:19
Hi @dantman, I have an update on this issue:

- Published a fix that omits the `chunks` option when reusing HTML webpack plugin instances from the user's webpack config, as discussed.
- Added a [troubleshooting](https://github.com/react-cosmos/react-cosmos/tree/master#troubleshooting) entry about the 404 errors you were getting and the potential fix of changing the source maps option. There may be a better way to handle this, but I can't afford to spend more time on this until I know how many other people are affected. Side note: Create React App is also [using `cheap-module-source-map`](https://github.com/facebook/create-react-app/blob/e51ea135e1a012f4e42e1d3cc230b9e6ef6576df/packages/react-scripts/config/webpack.config.js#L158). And source maps (webpack-generated at least) are an [ongoing issue](https://github.com/webpack/webpack/issues/3165) in general.

Please try the latest at `react-cosmos@5.0.0-beta.5` and let me know if you have any other issues. Closing this for now.

**Closed by skidding** 2019-10-05 09:19 UTC
Labels: hmm
